# ~/.config/starship.toml
continuation_prompt = "▶▶ "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red) "
vicmd_symbol = "[▶](bold green)"

[battery]
disabled = true


[aws]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
style = "bold blue"
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
disabled = false
style = "bold red"

[git_metrics]
disabled = false

[git_state]
disabled = false

[git_status]
disabled = false
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "fg:208"

[helm]
disabled = true

[kubernetes]
style = 'dimmed white'
format = '[\[ $context $namespace \]]($style) '
disabled = false
symbol = ''

[package]
disabled = true

[python]
disabled = true
format = ' [${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[terraform]
disabled = true

[time]
disabled = true
time_format = "%T"
utc_time_offset = "0"
style = "bold #FFCC00"

[golang]
disabled = true
