#!/bin/bash
# graphite-metric-bulk-create - quick hack to generate new metrics based on list of hostnames and metric paths and DSP ID lists
# intended to be used with graphite-metric-listed tool
# c Sat Mar 21 12:04:51 PDT 2015 smb - useful for avoiding graphite whisper create() delays when building out brand new datacenter INFRA-254

# Variables
METRICPATH="/ramdisk/whisper/metrics/"
MYDC=`hostname -f | cut -c 14-17`
MYCAPS=`echo $MYDC | tr a-z A-Z`
RETAIN="60s:7d 15m:62d 60m:1y"

# Arguments
METRICLIST=$1
HOSTLIST=$2
DSPLIST=$3
if [ ! $3 ]; then
        echo "ERROR: Three arguments are required. Usage: $0 <path-to-metric-list> <path-to-host-list> <path-to-dsp-list>"
        echo "To generate a metric list, see the graphite-metric-lister tool. The host/dsp lists should be one per line."
        exit
fi

# Loop over metrics, then hosts, creating metrics based on argument paths via whisper-create.py (iterating over DSPs when needed)
for METRIC in `cat $METRICLIST`;do
        SEARCH=`echo $METRIC | awk -F"XXhostnameXX" '{print $1}' | rev | cut -d'/' -f1 | rev`
        for LISTEDHOST in `cat $HOSTLIST | grep $SEARCH`;do
                HOST=`echo $LISTEDHOST | tr '.' '_'`
                HOSTGROUP=`echo $HOST | cut -c1-9 | tr a-z A-Z`"-"`echo $HOST | cut -c 14-17 | tr a-z A-Z`
                PHOST=`echo $HOST | cut -c 1-8`"XXhostnameXX_${MYDC}_fanops_net"
                PHOSTGROUP=`echo $HOST | cut -c 1-8 | tr a-z A-Z`"XXhostgroupXX-${MYCAPS}"
		if [[ $METRIC == *"XXdspidXX"* ]]; then
			for DSP in `cat $DSPLIST`; do
                		CREATEPATH=`echo $METRIC | grep $PHOST | sed "s/$PHOST/$HOST/g;s/$PHOSTGROUP/$HOSTGROUP/g;s/XXdspidXX/$DSP/g"`
                		CREATECOMMAND="/usr/bin/whisper-create.py $CREATEPATH $RETAIN"
                		mkdir -p `dirname $CREATEPATH`
                		$CREATECOMMAND &>/dev/null
			done
		else
                	CREATEPATH=`echo $METRIC | grep $PHOST | sed "s/$PHOST/$HOST/g;s/$PHOSTGROUP/$HOSTGROUP/g"`
                	CREATECOMMAND="/usr/bin/whisper-create.py $CREATEPATH $RETAIN"
                	mkdir -p `dirname $CREATEPATH`
                	$CREATECOMMAND &>/dev/null
		fi
        done
done

